### ISSUE TITLE
Add button to copy shareable text

### ISSUE THREAD

**Issue by julia-smith** [INN/republication-tracker-tool#15]
Add a button to the bottom of the modal to copy content from textarea to clipboard. You can do that in straight javascript these days, so let's go ahead and do that.

Example: https://codepen.io/shaikmaqsood/pen/XmydxJ/

**Comment by eidietrich** [comment]
Hey — so first off thanks for building this!

A minor bug to report with the copy shareable text button (our test site is running Wordpress 5.2.1 and Largo 0.6.3, the plugin is as I downloaded it 10 minutes ago).

The "copy to clipboard" button on the "republish this article" popup appears to be copying everything as uppercase text:

![image](https://user-images.githubusercontent.com/3946752/58738916-0c51e380-83c5-11e9-8ff0-f09bfc0cfdc1.png)

--> As previewed in a codepen
![image](https://user-images.githubusercontent.com/3946752/58739023-7b2f3c80-83c5-11e9-900c-a3f58b7c4e8e.png)

**Comment by benlk** [comment]
Thanks for reporting this, Eric! Can you give us a link to that codepen?

**Comment by joshdarby** [comment]
@eidietrich Could you also let us know what OS and browser you're using? I'm unable to recreate the bug on OS X 10.14.4 in Chrome 74.0.3729.157 and Firefox 66.0.5.
