### ISSUE TITLE
Is tracker link functioning properly?

### ISSUE THREAD

**Issue by benlk** [INN/republication-tracker-tool#48]
Seen in the text box at http://nmindepth.com/2019/06/03/lobbying-influence-game-largely-in-the-dark/ :

```html
<p>This <a target="_blank" href="http://nmindepth.com/2019/06/03/lobbying-influence-game-largely-in-the-dark/">article</a> first appeared on <a target="_blank" href="http://nmindepth.com">New Mexico In Depth</a> and is republished here under a Creative Commons license.<img id="republication-tracker-tool-source" src="http://nmindepth.com/wp-content/plugins/republication-tracker-tool/?republication-pixel=true&amp;post=375566&amp;ga=UA-34734870-1"></p>
```

When copied using the button:

```html
<p>This <a target="_blank" href="http://nmindepth.com/2019/06/03/lobbying-influence-game-largely-in-the-dark/">article</a> first appeared on <a target="_blank" href="http://nmindepth.com">New Mexico In Depth</a> and is republished here under a Creative Commons license.<img id="republication-tracker-tool-source" src="http://nmindepth.com/wp-content/plugins/republication-tracker-tool/?republication-pixel=true&amp;post=375566&amp;ga=UA-34734870-1"></p>
```

**Comment by joshdarby** [comment]
> ```
> <p>This <a target="_blank" href="http://nmindepth.com/2019/06/03/lobbying-influence-game-largely-in-the-dark/">article</a> first appeared on <a target="_blank" href="http://nmindepth.com">New Mexico In Depth</a> and is republished here under a Creative Commons license.<img id="republication-tracker-tool-source" src="http://nmindepth.com/wp-content/plugins/republication-tracker-tool/?republication-pixel=true&amp;post=375566&amp;ga=UA-34734870-1"></p>
> ```
> 
> 
> ```
> <p>This <a target="_blank" href="http://nmindepth.com/2019/06/03/lobbying-influence-game-largely-in-the-dark/">article</a> first appeared on <a target="_blank" href="http://nmindepth.com">New Mexico In Depth</a> and is republished here under a Creative Commons license.<img id="republication-tracker-tool-source" src="http://nmindepth.com/wp-content/plugins/republication-tracker-tool/?republication-pixel=true&amp;post=375566&amp;ga=UA-34734870-1"></p>
> ```

@benlk aren't those two identical? 🤔

**Comment by benlk** [comment]
Right, I didn't fully specify the bug.

Some of the `&` in the link are being converted to `&amp;` which is causing the tracker link to fail to load the image.

`true&amp;post=375566&amp;ga=UA-34734870-1`

**Comment by joshdarby** [comment]
@benlk Makes sense. _Assuming_ it's pasted into WP, the `&amp;`'s should be converted to `&` when the post is rendered. But I agree we should fix it.
