### ISSUE TITLE
Photos are not showing up in republished content

### ISSUE THREAD

**Issue by MirandaEcho** [INN/republication-tracker-tool#49]
In Depth NM reports that images are not republishing as they should be.  We should look into this further.

**Comment by joshdarby** [comment]
@MirandaEcho It looks like the way the plugin was originally built included stripping out specific elements from the content, such as images.

https://github.com/INN/republication-tracker-tool/blob/9768f76ee7265b9d2e732362037f9d9fa49ec4cb/includes/shareable-content.php#L22-L30

**Comment by MirandaEcho** [comment]
Confirmed, we want to include:
Images and associated content
Audio and associated content
Video and associated content
Button (but add instructions to documentation about full paths rather than relative)

**Comment by joshdarby** [comment]
@MirandaEcho Should this still be tagged as a bug or should it be an enhancement since it was intended to begin with?
